name: Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./app
        run: |
          npm install

      - name: Build frontend
        working-directory: ./app
        run: |
          npm run build

      - name: Run tests (frontend)
        working-directory: ./app
        run: |
          npm run test

      - name: Install Vercel CLI & Deploy Client app
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information for Frontend
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts for Frontend
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Frontend Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}